[package]
name = "siegu-signal"
version = "0.1.0"
description = "Standalone Siegu signalling server for self-hosting"
authors = ["Denzyl Dick"]
license-file = "../../LICENSE"
edition = "2021"

[[bin]]
name = "siegu-signal"
path = "src/main.rs"

[dependencies]
siegu-core = { workspace = true, default-features = false }
tokio = { workspace = true }
